server:
  port: 8887

mybatis:
  mapper-locations: classpath:life/majiang/community/mapper/*.xml
  type-aliases-package: life.majiang.community.model

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
